<a href="https://colab.research.google.com/github/tarannump096-cpu/CNN/blob/main/CNN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def convolution_technique(image_matrix,filter_matrix):
    output_matrix=np.zeros((4,4))
    for i in range(4):
        for j in range(4):
            extract_matrix=image_matrix[i:i+3,j:j+3]
            con_result=extract_matrix * filter_matrix
            output_matrix[i,j]=np.sum(con_result)
    return output_matrix

In [ ]:
def ReLu(x):
    return np.maximum(0, x)

image_matrix=np.array([[1,2,3,4,5,6],
                      [0,1,2,3,4,5],
                      [0,0,1,2,3,4],
                      [0,0,0,3,4,5],
                      [1,1,1,1,5,6],
                      [1,2,1,2,3,4]])
filter_matrix=np.array([[1,2,3],
                        [4,5,6],
                        [0,0,1]])
con_output=ReLu(convolution_technique(image_matrix,filter_matrix))

In [ ]:
def ReLu(x):
    return np.maximum(0,x)

In [ ]:
ReLu(con_output)

array([[32., 54., 76., 98.],
       [14., 34., 56., 78.],
       [ 4., 27., 58., 88.],
       [16., 26., 60., 95.]])

In [ ]:
con_output

array([[32., 54., 76., 98.],
       [14., 34., 56., 78.],
       [ 4., 27., 58., 88.],
       [16., 26., 60., 95.]])

In [ ]:
def max_pooling(con_output):

    pool_output = np.zeros((2,2))

    for i in range(0, 4, 2):
        for j in range(0, 4, 2):

            extract_matrix = con_output[i:i+2, j:j+2]

            pool_output[i//2, j//2] = np.max(extract_matrix)

    return pool_output


# Max Pooling Result
pool_output = max_pooling(con_output)

print("\nMax Pooling Output:\n")
print(pool_output)


Max Pooling Output:

[[54. 98.]
 [27. 95.]]
