<a href="https://colab.research.google.com/github/tarannump096-cpu/CNN/blob/main/CNN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def max_pooling(output_matrix,pooling_value):
    pooling_matrix=np.zeros((pooling_value,pooling_value))
    row=0
    for i in range(0,4,2):
        col=0
        for j in range(0,4,2):
            extract_matrix=output_matrix[i:i+2,j:j+2]
            max_result=np.max(extract_matrix)
            pooling_matrix[row,col]=max_result
            col+=1
        row+=1

    return  pooling_matrix

In [3]:
output_matrix=np.arange(0,16).reshape(4,4)

In [4]:
pooling_value=2
max_pooling(output_matrix,pooling_value)

array([[ 5.,  7.],
       [13., 15.]])

In [5]:
def min_pooling(output_matrix,pooling_value):
    pooling_matrix=np.zeros((pooling_value,pooling_value))
    row=0
    for i in range(0,4,2):
        col=0
        for j in range(0,4,2):
            extract_matrix=output_matrix[i:i+2,j:j+2]
            max_result=np.min(extract_matrix)
            pooling_matrix[row,col]=max_result
            col+=1
        row+=1

    return  pooling_matrix

In [6]:
output_matrix=np.arange(0,16).reshape(4,4)
pooling_value=2
min_pooling(output_matrix,pooling_value)

array([[ 0.,  2.],
       [ 8., 10.]])

In [7]:
def mean_pooling(output_matrix,pooling_value):
    pooling_matrix=np.zeros((pooling_value,pooling_value))
    row=0
    for i in range(0,4,2):
        col=0
        for j in range(0,4,2):
            extract_matrix=output_matrix[i:i+2,j:j+2]
            max_result=np.mean(extract_matrix)
            pooling_matrix[row,col]=max_result
            col+=1
        row+=1

    return  pooling_matrix

In [8]:
output_matrix=np.arange(0,16).reshape(4,4)
pooling_value=2
mean_pooling(output_matrix,pooling_value)

array([[ 2.5,  4.5],
       [10.5, 12.5]])